// Code generated by ogen, DO NOT EDIT.

package people_v1

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AddEmail implements addEmail operation.
//
// Добавить email человеку.
//
// POST /api/v1/people/{id}/emails
func (UnimplementedHandler) AddEmail(ctx context.Context, req *Email, params AddEmailParams) (r AddEmailRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AddFriend implements addFriend operation.
//
// Добавить друга человеку.
//
// POST /api/v1/people/{id}/friends
func (UnimplementedHandler) AddFriend(ctx context.Context, req *AddFriendReq, params AddFriendParams) (r AddFriendRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreatePerson implements createPerson operation.
//
// Создать нового человека.
//
// POST /api/v1/create
func (UnimplementedHandler) CreatePerson(ctx context.Context, req *PostCreatePerson) (r CreatePersonRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetFriends implements getFriends operation.
//
// Получить список друзей человека.
//
// GET /api/v1/people/{id}/friends
func (UnimplementedHandler) GetFriends(ctx context.Context, params GetFriendsParams) (r GetFriendsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListPeople implements listPeople operation.
//
// Получить список всех людей.
//
// GET /api/v1/people
func (UnimplementedHandler) ListPeople(ctx context.Context) (r ListPeopleRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SearchPerson implements SearchPerson operation.
//
// Поиск человека по ID или фамилии (одно из).
//
// GET /api/v1/people/search
func (UnimplementedHandler) SearchPerson(ctx context.Context, params SearchPersonParams) (r SearchPersonRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdatePerson implements updatePerson operation.
//
// Изменить информацию о человеке.
//
// PATCH /api/v1/people/search
func (UnimplementedHandler) UpdatePerson(ctx context.Context, req *UpdatePerson, params UpdatePersonParams) (r UpdatePersonRes, _ error) {
	return r, ht.ErrNotImplemented
}
