// Code generated by ogen, DO NOT EDIT.
package people_v1

type AddEmailRes interface {
	addEmailRes()
}

type AddFriendRes interface {
	addFriendRes()
}

type CreatePersonRes interface {
	createPersonRes()
}

type GetFriendsRes interface {
	getFriendsRes()
}

type ListPeopleRes interface {
	listPeopleRes()
}

type SearchPersonRes interface {
	searchPersonRes()
}

type UpdatePersonRes interface {
	updatePersonRes()
}
