// Code generated by ogen, DO NOT EDIT.

package people_v1

// OperationName is the ogen operation name
type OperationName = string

const (
	AddEmailOperation     OperationName = "AddEmail"
	AddFriendOperation    OperationName = "AddFriend"
	CreatePersonOperation OperationName = "CreatePerson"
	GetFriendsOperation   OperationName = "GetFriends"
	ListPeopleOperation   OperationName = "ListPeople"
	SearchPersonOperation OperationName = "SearchPerson"
	UpdatePersonOperation OperationName = "UpdatePerson"
)
